"""Assemble the dashboard into one self-contained HTML document.

This module is the seam the whole design rests on: the Streamlit
Dashboards view and the exported HTML report are **the same artifact**,
built by the same function. The app embeds it in a
``streamlit.components.v1.html`` iframe; the export writes it to a file.
Neither has a second implementation to drift from the other.

Self-contained means self-contained: styles, both engine modules and the
fact table are inlined. The output opens from a USB stick with no server,
no CDN and no network — the same standard
:mod:`~pm4py_ucm.algo.discovery.families.report` already meets.

Module inlining
---------------
``dash-ui.js`` imports ``dash-engine.js``. A file:// or ``srcdoc`` page
cannot resolve that relative specifier, so the two are stitched into one
module script: the engine is wrapped in an IIFE that returns its exports
as the ``E`` namespace the UI already expects, and the UI's import
statement is dropped.

The export list is derived from the source rather than hand-maintained
(:func:`_module_exports`), so adding an ``export`` to the engine does not
silently fail to reach the UI at runtime.
"""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence

from .catalog import catalog_json
from .contract import FactTable

ASSETS = Path(__file__).parent / "assets"

#: Matches the exported bindings of the engine/UI modules. Both files use
#: only the ``export <decl>`` form; the ``export {...}`` list form would
#: not be seen here, so it must not be introduced without updating this.
_EXPORT_RE = re.compile(
    r"^export\s+(?:async\s+)?(?:function|const|let|var|class)\s+"
    r"([A-Za-z_$][\w$]*)",
    re.M,
)

# Matches an ES import statement, including the multi-line
# ``import { a, b } from "…";`` form dash-report uses — non-greedy up to
# the first ``from "…";`` so it never swallows a following statement.
_IMPORT_RE = re.compile(
    r"^import\b[\s\S]*?from\s*[\"'][^\"']+[\"'];", re.M)


def _read(name: str) -> str:
    return (ASSETS / name).read_text(encoding="utf-8")


def _module_exports(src: str) -> List[str]:
    names = _EXPORT_RE.findall(src)
    if not names:
        raise RuntimeError(
            "No exports found while inlining a dashboard asset — the "
            "export syntax changed and _EXPORT_RE no longer matches it."
        )
    return names


def _strip_module_syntax(src: str) -> str:
    """Turn a module into plain script body: no imports, no ``export``."""
    src = _IMPORT_RE.sub("", src)
    return re.sub(r"^export\s+", "", src, flags=re.M)


def _script_json(value: Any) -> str:
    """JSON safe to embed in a ``<script>`` element.

    Any literal ``<`` inside the JSON is escaped to its ``\\u003c`` form.
    That neutralises both ``</script>`` (which would end the element
    early) and ``<!--`` (the legacy HTML comment parse) in one stroke,
    and — unlike escaping ``<!--`` to ``<\\!--`` — it stays **valid
    JSON**: ``\\u003c`` is a Unicode escape, whereas ``\\!`` is not a
    legal escape and makes ``JSON.parse`` throw. That mattered the moment
    the config carried a graphviz SVG, whose ``<!-- Generated by graphviz
    -->`` comment tripped exactly this.
    """
    return (json.dumps(value, separators=(",", ":"), ensure_ascii=False)
            .replace("<", "\\u003c"))


def _script_body(src: str) -> str:
    """JS source safe to embed in a ``<script>`` element.

    The HTML parser does not know JS: it ends the element at the first
    ``</script`` in the raw text, wherever it appears — inside a string,
    a regex, or a comment. Everything after it lands in the document
    body as text and the page is silently broken.

    That is not hypothetical. A comment in ``dash-ui.js`` *explaining*
    this very escaping mentioned ``</script>`` in prose, and truncated
    the bundle at exactly that word.

    ``<\\/script`` is identical to ``</script`` for JS — ``\\/`` is just
    an escaped forward slash — so the transform is safe in strings and
    regexes alike, and in a comment it is only text.
    """
    return (re.sub(r"</(script)", r"<\\/\1", src, flags=re.I)
            .replace("<!--", "<\\!--"))


def bundle_script() -> str:
    """The engine, UI and report renderer as one runnable module script.

    The engine is wrapped in an IIFE exposing its exports as ``E``; the UI
    and report modules are concatenated after it with their module syntax
    stripped, so the report can reference ``Dashboard``/``h``/``E`` as
    bundle-scope names. The report is never loaded as a standalone module
    — only ever inside this bundle — so its ``import`` lines exist purely
    for editor clarity and are stripped here.
    """
    engine = _read("dash-engine.js")
    ui = _read("dash-ui.js")
    report = _read("dash-report.js")
    names = _module_exports(engine)
    return _script_body(
        "const E = (() => {\n"
        + _strip_module_syntax(engine)
        + "\nreturn {" + ", ".join(names) + "};\n})();\n"
        + _strip_module_syntax(ui)
        + "\n" + _strip_module_syntax(report)
    )


_TEMPLATE = """<!DOCTYPE html>
<html lang="en"%(html_theme)s>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>%(title)s</title>
<style>
/* The page behind the dashboard. It has to follow the theme too, or a
   dark dashboard sits on a white page — and the browser paints this
   before any script runs, so it cannot wait to be told. */
html, body { margin: 0; padding: 0; background: #faf9f7; color-scheme: light dark; }
@media (prefers-color-scheme: dark) {
  html:not([data-theme="light"]), html:not([data-theme="light"]) body {
    background: #14161b;
  }
}
html[data-theme="dark"], html[data-theme="dark"] body { background: #14161b; }
html[data-theme="light"], html[data-theme="light"] body { background: #faf9f7; }
%(css)s
</style>
</head>
<body>
<div id="pm-root"></div>
<script type="application/json" id="pm-data">%(payload)s</script>
<script type="module">
%(bundle)s

const cfg = JSON.parse(document.getElementById("pm-data").textContent);
try {
  const el = document.getElementById("pm-root");
  // One artifact, two shapes: a report clone sets mode:"report" and boots
  // the Report renderer; everything else is a Dashboard.
  if (cfg.mode === "report") {
    window.pmReport = new Report(el, cfg);
  } else {
    // Exposed so a host page (or a test) can read the built widget specs
    // back out — the only channel out of the iframe.
    window.pmDashboard = new Dashboard(el, cfg);
  }
} catch (err) {
  document.getElementById("pm-root").innerHTML =
    '<div style="padding:20px;font:13px system-ui;color:#8f001a">' +
    'Failed to start: ' + String(err && err.message || err) +
    '</div>';
  throw err;
}
</script>
</body>
</html>
"""


def dashboard_html(
    table: FactTable,
    *,
    specs: Optional[Sequence[Dict[str, Any]]] = None,
    filters: Optional[Sequence[Dict[str, Any]]] = None,
    name: str = "Dashboard",
    read_only: bool = False,
    renders: Optional[Dict[str, str]] = None,
    storage_key: Optional[str] = None,
    title: Optional[str] = None,
    theme: Optional[str] = None,
    pending_pin: Optional[Dict[str, Any]] = None,
    model_svg: Optional[Dict[str, str]] = None,
) -> str:
    """Build the self-contained dashboard document.

    Parameters
    ----------
    table
        The fact table; its payload is embedded.
    specs
        Widget specs to start with. In the app these seed a new
        dashboard (the browser's saved set wins afterwards); in the
        export they *are* the dashboard.
    filters
        Dashboard-level filters the page opens with. Set by the page's
        own ⬇ Export so a dashboard sent to answer a specific question
        opens on that question.
    read_only
        ``True`` for the export. The reader keeps every way of
        *interrogating* the dashboard — filters, drill-down, axis swap,
        CSV, scorecard — and loses only the ways of *restructuring* it
        (adding and removing widgets). A read-only page also leaves the
        browser's saved widgets alone, so opening an export cannot
        clobber a dashboard the same person built in the app.
    renders
        ``{"ucm": <img src>, "bpmn": <img src>}`` for model widgets.
        Values are used verbatim as ``<img src>``, so pass ``data:`` URIs
        to keep the document self-contained.
    storage_key
        Namespaces the browser-side saved widgets. Defaults to the log
        name, so two logs do not share one dashboard.
    theme
        ``"light"`` / ``"dark"`` to pin the palette, or ``None`` (the
        default) to follow the viewer's ``prefers-color-scheme``.

        An embedded island should pass its host's *active* theme: a
        Streamlit app can be set to dark on a light OS, and then the OS
        preference is the wrong answer. A standalone export should leave
        it ``None`` — there is no host to ask, and it then tracks the
        reader's system theme live.
    pending_pin
        ``{"id": <unique per request>, "spec": <widget spec>}`` — a
        widget the host wants added, as "Pin to dashboard" on the Model
        view does.

        The host cannot add it directly: ``components.html`` is one-way
        and the widgets live in the browser. So it travels in the config
        and the island applies it. Because the config is re-sent on every
        rerun, ``id`` must be **fresh per request** — the island
        remembers the ids it has applied, and a reused one would either
        be ignored or breed a duplicate widget on every interaction.

    Returns
    -------
    str
        A complete HTML document — hand it to
        ``streamlit.components.v1.html`` or write it to a file.
    """
    if theme not in (None, "light", "dark"):
        raise ValueError(
            f"theme must be 'light', 'dark' or None, not {theme!r}"
        )
    cfg = {
        "payload": table.to_payload(),
        "catalog": catalog_json(interval_log=table.interval_log),
        "specs": list(specs or []),
        "filters": list(filters or []),
        "name": name,
        "readOnly": bool(read_only),
        "renders": renders or {},
        "storageKey": storage_key or table.log_name,
        "theme": theme,
        "pendingPin": pending_pin,
        # Both notations as inline SVG for the session report's model
        # section — the one thing the browser cannot render itself, so the
        # backend embeds it here for the client-built report to lift.
        "modelSvg": model_svg or {},
    }
    return _TEMPLATE % {
        # On <html> rather than set by script: the browser paints the page
        # background before any script runs, so a pinned dark theme would
        # otherwise flash white on every load.
        "html_theme": f' data-theme="{theme}"' if theme else "",
        "title": _escape(title or f"{name} — {table.log_name}"),
        "css": _read("dash-styles.css"),
        "payload": _script_json(cfg),
        "bundle": bundle_script(),
    }


def write_dashboard(path, table: FactTable, **kwargs) -> str:
    """Write :func:`dashboard_html` to ``path``; returns the path."""
    p = Path(path)
    p.write_text(dashboard_html(table, **kwargs), encoding="utf-8")
    return str(p)


def _escape(text: str) -> str:
    return (str(text).replace("&", "&amp;").replace("<", "&lt;")
            .replace(">", "&gt;"))
